password = [ 0x30, 0x30, 0x30, 0x30, 0x30, 0x30 ]
brightness = 100
blink_interval = 30
auto_pause = 480
jira_user = "your-user@domain.com"
jira_token = "your-token"
jira_base_url = "https://your-domain.atlassian.net"
jira_board_id = "999"
jira_jql_issue_filter = ""

[[sides]]
facet = 1
name = "(Kaffee) Pause"
color.red = 0
color.green = 0
color.blue = 0xFFFF
task = "Simple"

[[sides]]
facet = 8
name = "Projekzeit"
color.red = 0xFFFF
color.green = 0xFFFF
color.blue = 0xFFFF
task = "Simple"

[[sides]]
facet = 12
name = "Infrastruktur"
color.red = 0xFFFF
color.green = 0
color.blue = 0
task = "Simple"
